# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: staging

on:
  push:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:latest
        ports: 
          - 3306
        env:
           MYSQL_USER: root
           MYSQL_PASSWORD: password
           MYSQL_DATABASE: freelancer
           MYSQL_ROOT_PASSWORD: password
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
  
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Verify MariaDB connection
      env:
        PORT: ${{ job.services.mariadb.ports[3306] }}
      run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
            sleep 1
          done
    - name: Test with Maven
      run: mvn test
