# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: staging

on:
  push:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest
    services:
       mysql:
         image: mysql:5.7
         env:
          MYSQL_ROOT_PASSWORD: password
         ports: 
           - 3306
         options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Verify MySQL connection from host
      run: |
        sudo apt-get install -y mysql-client
        mysql --host 127.0.0.1 --port 3306 -uroot -ppassword -e "SHOW DATABASES"
        mysql --host 127.0.0.1 --port 3306 -uroot -ppassword -e "CREATE DATABASE freelancer"
        mysql --host 127.0.0.1 --port 3306 -uroot -ppassword freelancer -e "source /home/runner/work/backend/backend/database_freelancer_v3.3_5.sql"
        mysql --host 127.0.0.1 --port 3306 -uroot -ppassword freelancer -e "select * from user where user_id = 1"
        mysql --host 127.0.0.1 --port 3306 -uroot -ppassword -e "status"
        ls
        pwd
        
    - name: Test with Maven
      run: mvn test
